language: generic 
services:
    - docker
before_install:
    - docker build -t docker-test -f Dockerfile.dev .
script:
    - docker run -e CI=true docker-test npm run test -- --coverage
deploy:
    provider: heroku
    api_key: $HEROKU_AUTH_TOKEN
    app: 
        master: n4d-docker-test